# MongoDB Atlas - pega aquí tu URI de Atlas
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=heladeria
 
# Puerto del servidor
server.port=${PORT:8080}
 
# JWT
jwt.secret=${JWT_SECRET}
 
