# MongoDB Atlas - pega aquí tu URI de Atlas
spring.data.mongodb.uri=mongodb+srv://admin:1234@mo.gziuz8l.mongodb.net/heladeria?retryWrites=true&w=majority&appName=MO
spring.data.mongodb.database=heladeria
 
# Puerto del servidor
server.port=8083
 
# JWT
jwt.secret=frosthub-heladeria-uis-secret-key-2025
 
